spring.application.name=UsersService
server.port=8060

spring.datasource.url=jdbc:postgresql://localhost:5432/user_profiles
spring.datasource.username=postgres
spring.datasource.password=hanae
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

jwt.refresh-token.expiration=604800000
rsa.publickey=classpath:keys/publicKey.pem
rsa.privatekey=classpath:keys/privateKey.pem